#baseURL = 'https://vineta.potashow.com/'
baseURL = '/'
languageCode = 'en-us'
title = 'My Books'

[taxonomies]
  series = 'series'
  tag = 'tags'
  author = 'author'

[imaging]
  [imaging.exif]
    disableDate = false
    disableLatLong = false
    excludeFields = ''
    includeFields = ''
# https://adriano.fyi/posts/2023/2023-07-04-making-hugo-static-sites-dynamic-with-htmx-and-go/
[module]
 [[module.mounts]]
 source = 'partials'
 target = 'content'

