local_backend:
  # when using a custom proxy server port
  # url: http://localhost:8081/api/v1
  # when accessing the local site from a host other than 'localhost' or '127.0.0.1'
  allowed_hosts: ['10.10.10.177']
backend:
  name: git-gateway
  branch: main
media_folder: /assets/img
public_folder: /img
collections:
  - name: "books"
    label: "Books"
    folder: "content/books"
    create: true
    slug: "{{title}}"
    eidtor: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Author', name: 'author', widget: 'string', default: "неизвестный" }
      - { label: 'Series', name: 'series', widget: 'string', default: "самостоятельный роман" }
      - { label: "Tags", name: "tags", widget: "list", default: ["18+"] }
      - label: "Image"
        name: "image"
        widget: "image"
        allow_multiple: false
        choose_url: true
        default: "/uploads/chocolate-dogecoin.jpg"
        media_library:
          config:
            multiple: false
      - { label: "Already Have", name: "have", widget: "boolean", default: true}
      - { label: 'Body', name: 'body', widget: 'markdown' }

