local_backend:
  allowed_hosts: []
backend:
  name: git-gateway
  branch: main
locale: "ru"
media_folder: src/assets/img
public_folder: /src/assets/img
collections:
  - name: "genre"
    label: "Жанры"
    label_singular: "Жанр"
    folder: "src/content/genre"
    create: true
    slug: "{{title}}"
    fields:
      - { label: "Жанр", name: "title", widget: "string" }
      - { label: "Описание", name: "body", widget: "markdown", default: " " }
  - name: "books"
    label: "Книги"
    label_singular: "Книгу"
    folder: "src/content/books"
    create: true
    slug: "{{title}}"
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - {
          label: "Автор",
          name: "author",
          widget: "string",
          default: "неизвестный",
        }
      - label: "Жанры"
        label_singular: "Жанр"
        name: "genre"
        widget: "relation"
        collection: "genre"
        search_fields: ["title"]
        value_field: "title"
        display_fields: ["{{title}}"]
      - {
          label: "Цикл",
          name: "series",
          widget: "string",
          default: "самостоятельный роман",
        }
      - { label: "Tags", name: "tags", widget: "list", default: ["18+"] }
      - label: "Обложка"
        name: "image"
        widget: "image"
        allow_multiple: false
        choose_url: true
        default: "/src/assets/img/sobor.jpeg"
        media_library:
          config:
            multiple: false
      - { label: "Уже есть", name: "have", widget: "boolean", default: true }
      - { label: "Описание", name: "body", widget: "markdown" }
